# Generated by Django 5.1.2 on 2024-11-02 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('heart_rate', models.IntegerField()),
                ('blood_pressure', models.CharField(max_length=255)),
                ('sleep_duration', models.IntegerField()),
                ('oxygen_saturation', models.IntegerField()),
                ('body_temperature', models.IntegerField()),
                ('bmi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('data_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='MainApp.dataentry')),
            ],
        ),
    ]
