# Generated by Django 5.1.2 on 2024-11-04 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='blood_pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='bmi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='body_temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='oxygen_saturation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='sleep_duration',
            field=models.FloatField(),
        ),
    ]
